name: Tests
on:
  push:
    branches:
      - main
      - '*.x'
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'
jobs:
  local-test:
    name: ubuntu20.04-py${{ matrix.python }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - {python: '3.12'}
          - {python: '3.11'}
          - {python: '3.10'}
          - {python: '3.9'}
          - {python: '3.8'}
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Install GCC and Make
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.8.2
          poetry install --with dev

      - name: Run Examples Test
        run: poetry run pytest -vs -n auto

  container-test:
    name: GCC Docker Container
    runs-on: ubuntu-latest
    container:
      image: gcc:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3-pip
          python3 -m pip install --upgrade pip --break-system-packages
          pip install poetry==1.8.2 --break-system-packages
          poetry install --with dev

      - name: Run Examples Test
        run: poetry run pytest -vs -n auto